## Numpy array and basic

In [3]:
import numpy as np

## Creating array from list

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("1D array: ", arr_1d)


1D array:  [1 2 3 4 5]
1D array:  [1 2 3 4 5]


### List vs numpy array

In [5]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1, 2, 3])      # element wise multiplication
print("Python array multiplication ", np_array * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


## Creating array from scratch

In [6]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("Sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.54009492 0.48147751 0.47104653]
 [0.79804365 0.07103045 0.78824547]]
Sequence array: 
 [ 0  2  4  6  8 10]


## Vector, Matrix and Tensor

In [7]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 4]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 4]]]


## Array Properties:

In [ ]:
arr = np.array([[1, 2, 3],
               [4, 5, 6]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("DType: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
DType:  int64


## Array Reshaping

In [12]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped array: ", reshaped)

flattened = reshaped.flatten()
print("Flattened array: ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("Raveled array: ", raveled)

# Transpose
transpose = reshaped.T
print("Transposed array: ", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
